app: srs-version
stage: dev

component: scf
name: im-service

inputs:
  name: ${name}-${stage}-${app}
  region: ${env:REGION}
  handler: index.main_handler
  runtime: Nodejs12.16
  timeout: 30
  role: SCF_QcsRole
  src: 
    bucket: srs-version-scf
    src: ./src
  environment:
    variables:
      REGION: ${env:REGION}
      DB_INTERNAL_SERVICE: db-internal-service-${stage}-${app}
      IM_INTERNAL_SERVICE: im-internal-service-${stage}-${app}
      IM_SDKAPPID: ${env:IM_SDKAPPID}
      IM_SECRETKEY: ${env:IM_SECRETKEY}
      IM_GROUP_SYSLOG: ${env:IM_GROUP_SYSLOG}
      JWT_SECRET: ${env:JWT_SECRET}
  cls:
    logsetId: ${env:SCF_LOGSET}
    topicId: ${env:SCF_LOGTOPIC}
  events:
    - apigw:
        parameters:
          environment: release
          serviceId: ${output:${stage}:${app}:apigw-service.serviceId}
          endpoints:
            - method: ANY # GET POST PUT DELETE HEAD ANY
              path: /im-service/v1/
              enableCORS: true
          protocols:
            - http
            - https
