app: srs-version
stage: dev

component: scf
name: im-service

inputs:
  name: ${name}-${stage}-${app}
  region: ${env:REGION}
  handler: index.main_handler
  timeout: 30
  runtime: Nodejs10.15
  src: 
    bucket: srs-version-scf
    src: ./src
  environment:
    variables:
      IM_SDKAPPID: ${env:IM_SDKAPPID}
      IM_SECRETKEY: ${env:IM_SECRETKEY}
      IM_ADMINISTRATOR: ${env:IM_ADMINISTRATOR}
  events:
    - apigw:
        parameters:
          environment: release
          serviceId: ${output:${stage}:${app}:apigw-service.serviceId}
          endpoints:
            - method: ANY # GET POST PUT DELETE HEAD ANY
              path: /im-service/v1/
              enableCORS: true
          protocols:
            - http
            - https
