app: srs-version
stage: dev

component: scf
name: im-internal-service

inputs:
  name: ${name}-${stage}-${app}
  region: ${env:REGION}
  handler: index.main_handler
  runtime: Nodejs10.15
  timeout: 30
  role: SCF_QcsRole
  src: 
    bucket: srs-version-scf
    src: ./src
  environment:
    variables:
      REGION: ${env:REGION}
      DB_SERVICE: db-service-${stage}-${app}
      IM_SDKAPPID: ${env:IM_SDKAPPID}
      IM_SECRETKEY: ${env:IM_SECRETKEY}
      IM_ADMINISTRATOR: ${env:IM_ADMINISTRATOR}
  events: []
