app: srs-version
stage: dev

component: websocket
name: ws-service

inputs:
  region: ${env:REGION}
  runtime: Nodejs10.15
  src: 
    bucket: srs-version-scf
    src: ./src
  faas:
    role: SCF_QcsRole
    name: ${name}-${stage}-${app}
    timeout: 10
    vpcConfig:
      vpcId: ${output:${stage}:${app}:vpc4-service.vpcId}
      subnetId: ${output:${stage}:${app}:vpc4-service.subnetId}
    environment:
      variables:
        API_SERVICE: api-service-${stage}-${app}
        MYSQL_HOST: ${output:${stage}:${app}:mysql-service.connection.ip}
        MYSQL_PORT: ${output:${stage}:${app}:mysql-service.connection.port}
        MYSQL_USER: root
        MYSQL_PASSWORD: ${output:${stage}:${app}:mysql-service.adminPassword}
  apigw:
    timeout: 300
    environment: release
    serviceId: ${output:${stage}:${app}:wsgw-service.serviceId}
    protocols:
      - http
      - https

# https://github.com/serverless-components/tencent-websocket/blob/master/docs/configure.md
