app: srs-version
stage: dev

component: scf
name: api-service

inputs:
  name: ${name}-${stage}-${app}
  region: ${env:REGION}
  description: ${stage}, ${env:DESCRIPTION}
  eip: false
  enableRoleAuth: true
  handler: main
  memorySize: 128
  namespace: default
  publicAccess: true
  runtime: Go1
  timeout: 3
  src: 
    bucket: srs-version-scf
    src: ./src
  environment:
    variables:
      REGION: ${env:REGION}
      MYSQL_DB: ${env:MYSQL_DB}
      MYSQL_HOST: ${output:${stage}:${app}:mysql-service.connection.ip}
      MYSQL_PORT: ${output:${stage}:${app}:mysql-service.connection.port}
      MYSQL_PASSWORD: ${output:${stage}:${app}:mysql-service.adminPassword}
  vpcConfig:
    vpcId: ${output:${stage}:${app}:vpc4-service.vpcId}
    subnetId: ${output:${stage}:${app}:vpc4-service.subnetId}
  events:
    - apigw:
        parameters:
          environment: release
          serviceId: ${output:${stage}:${app}:apigw-service.serviceId}
          endpoints:
            - method: ANY # GET POST PUT DELETE HEAD ANY
              path: /service/v1/releases
          protocols:
            - http
            - https

# https://github.com/serverless-components/tencent-scf/blob/master/docs/configure.md
