app: srs-version
stage: dev

component: scf
name: api-service

inputs:
  name: ${name}-${stage}-${app}
  region: ${env:REGION}
  description: ${stage}, ${env:DESCRIPTION}
  eip: false
  enableRoleAuth: true
  handler: main
  memorySize: 128
  namespace: default
  publicAccess: true
  runtime: Go1
  timeout: 3
  src: 
    bucket: srs-version-scf
    src: ./src
  environment:
    variables:
      REGION: ${env:REGION}
  events:
    - apigw:
        parameters:
          environment: release
          serviceId: ${output:${stage}:${app}:apigw-service.serviceId}
          endpoints:
            - method: GET
              path: /service/v1/releases
          protocols:
            - http
            - https

# https://github.com/serverless-components/tencent-scf/blob/master/docs/configure.md
