app: srs-version
stage: dev

component: scf
name: api-service

inputs:
  name: ${name}-${stage}-${app}
  region: ap-guangzhou
  handler: index.main_handler
  runtime: Nodejs12.16
  timeout: 30
  role: SCF_QcsRole
  src: 
    bucket: srs-version-scf
    src: ./
  environment:
    variables:
      REGION: ap-guangzhou
  events:
    - apigw:
        parameters:
          environment: release
          serviceId: ${output:${stage}:${app}:apigw-service.serviceId}
          endpoints:
            - method: ANY # GET POST PUT DELETE HEAD ANY
              path: /service/v1/releases
              enableCORS: true
          protocols:
            - http
            - https

# https://github.com/serverless-components/tencent-scf/blob/master/docs/configure.md
