app: srs-version
stage: dev

component: scf
name: api-service

inputs:
  name: ${name}-${stage}-${app}
  region: ${env:REGION}
  handler: index.main_handler
  runtime: Nodejs10.15
  timeout: 30
  role: SCF_QcsRole
  src: 
    bucket: srs-version-scf
    src: ./src
  environment:
    variables:
      REGION: ${env:REGION}
      DB_SERVICE: db-service-${stage}-${app}
      IM_SERVICE: im-service-${stage}-${app}
      MYSQL_DB: ${env:MYSQL_DB}
      MYSQL_HOST: ${output:${stage}:${app}:mysql-service.connection.ip}
      MYSQL_PORT: ${output:${stage}:${app}:mysql-service.connection.port}
      MYSQL_PASSWORD: ${output:${stage}:${app}:mysql-service.adminPassword}
      IM_GROUP_SYSLOG: ${env:IM_GROUP_SYSLOG}
  vpcConfig:
    vpcId: ${output:${stage}:${app}:vpc4-service.vpcId}
    subnetId: ${output:${stage}:${app}:vpc4-service.subnetId}
  events:
    - apigw:
        parameters:
          environment: release
          serviceId: ${output:${stage}:${app}:apigw-service.serviceId}
          endpoints:
            - method: ANY # GET POST PUT DELETE HEAD ANY
              path: /service/v1/releases
          protocols:
            - http
            - https

# https://github.com/serverless-components/tencent-scf/blob/master/docs/configure.md
